modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
	modId="skilltree"
	version="0.4.9a"
	displayName="Passive Skill Tree"
	authors="Daripher"
	description='''Adds passive skill tree with player class system'''
	credits='''Thanks to: LittleOdie for some ideas. Prince_Vladislav for some of the icons. All the modpack makers who use my mod. All the people on my discord server.'''
	
[[dependencies.skilltree]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.skilltree]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
